name: Growth

on:
  schedule:
    # UTC 时间 0 点运行一次
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.14.2'

      - name: Depend install and serve
        run: |
           node ./rank.js
